<a href="https://colab.research.google.com/github/jebinshaju/machine_learning/blob/main/pandasandnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas

In [ ]:
import pandas as pd

df =pd.read_csv("/content/drive/MyDrive/data set/demo.csv")
df["DA"]=0
df["TAX"]=0
df["NetPay"]=0
df["DA"] = (df['BASIC PAY']*20/100)
df["TAX"] = (df['BASIC PAY']*10/100)
df["NetPay"] = (df['BASIC PAY']+df['DA'])-df["TAX"]


df

EMPNO    NAME        DESIGNATION  BASIC PAY       DA      TAX    NetPay
0    101   Jacob  managing director     130000  26000.0  13000.0  143000.0
1    102   paola    project manager      70000  14000.0   7000.0   77000.0
2    103  willam        team leader      40000   8000.0   4000.0   44000.0
3    104    kear        team leader      30000   6000.0   3000.0   33000.0
4    105   eliot        content dev      30000   6000.0   3000.0   33000.0
5    106     ded        content dev      30000   6000.0   3000.0   33000.0
6    107    marg        content dev      30000   6000.0   3000.0   33000.0
7    108     heh             devops      32000   6400.0   3200.0   35200.0
8    109     geo             devops      44000   8800.0   4400.0   48400.0
9    110     ken             devops      55000  11000.0   5500.0   60500.0

In [ ]:

s =pd.Series([1,2,3],index=["a","b","c"])
s["b"]

2

In [ ]:
ph ={"a":1,"b":2}
s=pd.Series(ph)
s


a    1
b    2
dtype: int64

In [ ]:
ph ={"RollNO":[1,2,3],"name":["ooo","ttt","rrr"],"Marks":[100,101,102]}
s=pd.DataFrame(ph,index=[1,2,3])
s


RollNO name  Marks
1       1  ooo    100
2       2  ttt    101
3       3  rrr    102

Numpy

In [ ]:
import numpy as np

z=np.zeros(6)
print(z)
z
o=np.sqrt(9)
print(o)
oneD=np.array([1,2,32,3,4])
print(oneD)
twoD = np.array([[1,2,3],[4,5,6]])
print(twoD)
print(type(twoD))
print(type(o))

print(twoD.size)
print(twoD.shape)

print(twoD.transpose())

[0. 0. 0. 0. 0. 0.]
3.0
[ 1  2 32  3  4]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
6
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
